---
name: ansible-test
'on':
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - galaxy.yml
      - plugins/doc_fragments/*.py
      - plugins/module_utils/*.psm1
      - plugins/modules/*.ps1
      - plugins/modules/*.py
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - plugins/doc_fragments/*.py
      - plugins/module_utils/*.psm1
      - plugins/modules/*.ps1
      - plugins/modules/*.py
defaults:
  run:
    working-directory: 'collections/ansible_collections/trippsc2/mdt'
jobs:
  sanity:
    name: Run ansible-test
    uses: trippsoft/github-actions/.github/workflows/ansible-test.yml@main
    with:
      working_directory: 'collections/ansible_collections/trippsc2/mdt'
      ansible_version: ${{ matrix.ansible_version }}
    strategy:
      fail-fast: false
      matrix:
        ansible_version:
          - '2.18'
          - '2.17'
          - '2.16'
